### ISSUE TITLE
Presence somehow stopped working

### ISSUE THREAD

**Issue by VojtaNesvadba** [sll552/DiscordBee#119] opened 2022-03-06 14:42 UTC
I don't know much about this tech-thing, but until today it worked well, authomatically uploaded covers to presence assets and everything, but now it like just from nothing stopped. I am using the latest version (v2.1.0).
Basically, it shows all the info, even the custom name I set on Discord Application, but it just doesn't update covers. It doesn't even show MusicBee logo on presence (which I experienced dissapeared from Presence assets, maybe I once missclicked when manually uploading covers, but it should upload back again by the plugin, or not? I also replaced it with the logo from source for the plugin, so this is not a problem).

UPDATE: I tried to unistall and set up new application for it. All I see is that is just stopped uploading assets to the Discord App.

**Comment by Gimzie** [comment] 2022-03-08 05:54
I seem to have the same problem. Was there an API change or something as of late?

**Comment by sll552** [comment] 2022-03-09 08:06
Without having tested anything. It can happen that the token in the leveldb changes and might become unreadable. For almost all cases of "it stopped working" the best thing you can do is the logout -> delete leveldb -> login dance. 

I will try to verify if there is anything else that changed (like API, limits, etc.) but I don't know when I will have time for that.

**Comment by VojtaNesvadba** [comment] 2022-03-09 09:36
I see deleting leveldb didn't work for me. Judging [https://discordstatus.com/](https://discordstatus.com/) there was no problem with developer portal. I may be wrong.

**Comment by Gimzie** [comment] 2022-03-10 21:14
Yep, I tried deleting my leveldb multiple times as usual, but DiscordBee doesn't seem to be uploading new cover images. It doesn't seem like I'm able to get it to use existing images either.

**Comment by sll552** [comment] 2022-03-11 08:12
I was able to reproduce it myself. It seems that discord finally stopped writing the auth token to the leveldb (which was bad security wise anyway) that means that the plugin is no longer able to use your login to upload the covers. I actually don't know why existing covers should not work because it seems like listing the already uploaded covers still works. 

Anyway this breaks the cover functionality and it will stay broken until #117 is done.

**Comment by Rings4** [comment] 2022-03-11 08:16
Strange, still working for me.

**Comment by sll552** [comment] 2022-03-11 08:34
maybe because there is still an old ldb file with a still working token. I also had an old file with a token in it but it expired and when I deleted the leveldb folder in the new files there was no token anymore.

**Comment by mileinmortal** [comment] 2022-03-16 04:38
is there anyway to upload manually the covers?

**Comment by anitsekS** [comment] 2022-04-21 18:48
any updates on when this will be fixed?

**Comment by seulgiism** [comment] 2022-04-23 13:43
i would like to know too ;3

**Comment by Elasder123** [comment] 2022-05-02 23:53
I hope there will be other methods to add covers, maybe a manual option?

**Comment by seanmiles** [comment] 2022-05-03 16:59
> I hope there will be other methods to add covers, maybe a manual option?

There is currently a manual way to add album art functionality: https://github.com/sll552/DiscordBee/issues/100#issuecomment-1013757465

In my experience it only works if the artwork is linked to the song in MusicBee and the song is in the same folder as the Cover.png you are uploading (separate folders, like discs, will not work).

![Discord_2022-05-03_09-56-58](https://user-images.githubusercontent.com/39392514/166502265-ace34cd1-202b-424b-84d7-c01cd0be5748.png)

**Comment by VelocityRa** [comment] 2022-05-10 04:48
@seanmiles 
Haven't been able to make it work.
Does it still work for you? 

> In my experience it only works if the artwork is linked to the song in MusicBee and the song is in the same folder as the Cover.png you are uploading (separate folders, like discs, will not work).

Does embedded art work?

**Comment by Elasder123** [comment] 2022-05-11 14:56
> > I hope there will be other methods to add covers, maybe a manual option?
> 
> There is currently a manual way to add album art functionality: [#100 (comment)](https://github.com/sll552/DiscordBee/issues/100#issuecomment-1013757465)
> 
> In my experience it only works if the artwork is linked to the song in MusicBee and the song is in the same folder as the Cover.png you are uploading (separate folders, like discs, will not work).
> 
> ![Discord_2022-05-03_09-56-58](https://user-images.githubusercontent.com/39392514/166502265-ace34cd1-202b-424b-84d7-c01cd0be5748.png)
> 
> Edit: I will add you still need to manually upload the pause, play, stop, and logo icons if those don't exist already (for first time setup, for example) in order for the album art functionality to start working. I pulled those icons from [the repo](https://github.com/sll552/DiscordBee/tree/master/Icons) and then used a custom image for the logo.
> 
> ![image](https://user-images.githubusercontent.com/39392514/166507809-90f1c175-7012-49f0-a736-032fd3d32228.png)

tried it and my album art is still not showing up XDD only the logo and the play, pause and stop

**Comment by Andrewsch24** [comment] 2022-05-20 00:33
> > I hope there will be other methods to add covers, maybe a manual option?
> 
> There is currently a manual way to add album art functionality: [#100 (comment)](https://github.com/sll552/DiscordBee/issues/100#issuecomment-1013757465)
> 
> In my experience it only works if the artwork is linked to the song in MusicBee and the song is in the same folder as the Cover.png you are uploading (separate folders, like discs, will not work).
> 
> ![Discord_2022-05-03_09-56-58](https://user-images.githubusercontent.com/39392514/166502265-ace34cd1-202b-424b-84d7-c01cd0be5748.png)
> 
> Edit: I will add you still need to manually upload the pause, play, stop, and logo icons if those don't exist already (for first time setup, for example) in order for the album art functionality to start working. I pulled those icons from [the repo](https://github.com/sll552/DiscordBee/tree/master/Icons) and then used a custom image for the logo.
> 
> ![image](https://user-images.githubusercontent.com/39392514/166507809-90f1c175-7012-49f0-a736-032fd3d32228.png)

Too much work, I'd rather wait for the "official" automated way.

**Comment by Rings4** [comment] 2022-05-20 00:55
> maybe because there is still an old ldb file with a still working token. I also had an old file with a token in it but it expired and when I deleted the leveldb folder in the new files there was no token anymore.

When does this token expire? I'm curious because my artwork still shows normally. I've been meaning to change the app name in the developer portal but I'm worried that will cause the token to expire and thus my artwork will stop displaying, is that the case?

**Comment by sll552** [comment] 2022-05-23 13:56
> When does this token expire? I'm curious because my artwork still shows normally. I've been meaning to change the app name in the developer portal but I'm worried that will cause the token to expire and thus my artwork will stop displaying, is that the case?

The token is your normal discord login token, so it should not be bound to anything related to the developer dashboard. But no guarantee on that.

**Closed** 2022-07-10 20:01 UTC
