### ISSUE TITLE
Any way to hide the track counts in the status?

### ISSUE THREAD

**Issue by instilledbee** [sll552/DiscordBee#40] opened 2020-06-27 03:54 UTC
First of all, thank you for this plugin.

I'm trying to customize the status that is sent to Discord but it seems I can't remove the track number and track count from the placeholder template. I've tried removing the values in the textboxes for them but it seems my changes didn't get saved. Is there any way to totally hide it?

Thanks again!

**Comment by sll552** [comment] 2020-06-29 09:45
This should work since it was fixed fixed in https://github.com/sll552/DiscordBee/issues/29 ?
Please tell me exactly what you are doing so I can try to replicate it. (ideally with a screenshot of the config)

**Comment by instilledbee** [comment] 2020-07-04 08:00
@sll552 I use empty strings in the text boxes for the track numbers. This is what my config looks like: 

![image](https://user-images.githubusercontent.com/5665389/86508036-446cf680-be0f-11ea-964e-f69e041c546f.png)

I am able to replicate it just by saving from DiscordBee's window and then re-opening it without closing/saving MusicBee's Preferences window. Although even if I do save the MusicBee preferences, DiscordBee's config still won't save.

I am using the latest release from Github (1.3.2)

**Comment by JezzaR-The-Proto** [comment] 2020-07-04 20:50
Hi, I'm getting the same issue here on version 1.3.2 aswell. I have made a video so you can fully see what's going on.
https://streamable.com/12e1cg

**Comment by JezzaR-The-Proto** [comment] 2020-07-07 17:45
Just a thing i've noticed, apparently this must only happen sometimes, since i've not updated from 1.3.2 but I no longer get the bug.
![Screenshot_561](https://user-images.githubusercontent.com/54776821/86821241-0fb4a580-c082-11ea-9646-279ba87776a5.png)

**Comment by sll552** [comment] 2020-07-07 20:06
This is just a guess but your file might be missing the tags for track numbers so they are not displayed. If it happens with the same track though it would be strange.

I was able to reproduce it but had no time to fix it yet, I will try next weekend

**Comment by JezzaR-The-Proto** [comment] 2020-07-08 11:54
> missing the tags for track numbers
Coming off of that point, if you set it to something that it is missing, eg Custom1 it does hide properly.

**Closed** 2020-09-26 15:06 UTC
