### ISSUE TITLE
how do i remove the track number?

### ISSUE THREAD

**Issue by bar-dot** [sll552/DiscordBee#29] opened 2020-03-05 08:49 UTC
replacing it with " " doesnt work

**Comment by sll552** [comment] 2020-03-05 09:03
I am just guessing that this is a possible duplicate of #27 

Could you please try the version linked in https://github.com/sll552/DiscordBee/issues/27#issuecomment-594153050

**Comment by bar-dot** [comment] 2020-03-07 06:00
> I am just guessing that this is a possible duplicate of #27
> 
> Could you please try the version linked in [#27 (comment)](https://github.com/sll552/DiscordBee/issues/27#issuecomment-594153050)

that fixed it :D thanks

**Closed** 2020-03-07 17:33 UTC
